# Generated by Django 2.2 on 2020-04-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200330_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
